controller:
  trajectories:
    default: centerline_deviate.csv
    wp2_name: centerline_deviate_inner.csv
    wp3_name: centerline_deviate_outer.csv
obstacle_detection:
  ttc_threshold: 1.0
  preprocess_conv_size: 3
  clearance: 0.15
is_sim: true
